### ISSUE TITLE
Ingress DNS registration not working on GCE (?)

### ISSUE THREAD

**Issue by tolbrino** [linki/mate#64]
This might be a misinterpretation of the documentation on my side and not a bug. In that case please consider this a question.

The environment is Google Container Engine. Kubernetes deployment file for `mate` looks like this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mate
    spec:
      containers:
        - name: mate
          image: registry.opensource.zalan.do/teapot/mate:v0.5.0
          args:
            - --producer=kubernetes
            - --kubernetes-format={{.Namespace}}-{{.Name}}.test.net
            - --consumer=google
            - --google-project=test
            - --google-zone=test-net
            - --google-record-group-id=test-cluster
```

There's a `traefik` service registered as a LoadBalancer in the Kubernetes cluster, which gets its DNS registered according to the format description properly. Then I've got some other service's with Ingress specs like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  creationTimestamp: 2017-01-16T15:40:14Z
  generation: 2
  labels:
    app: eating-otter-test
  name: eating-otter-test
  namespace: default
spec:
  rules:
  - host: testservice.test.net
    http:
      paths:
      - backend:
          serviceName: eating-otter-test
          servicePort: 80
  tls:
  - hosts:
    - testservice.test.net
    secretName: testservice-test-tls
status:
  loadBalancer: {}
```

However, `mate` doesn't pick up on the hostnames and instead logs this: `msg="[Ingress] The load balancer of ingress 'default/eating-otter-test' does not have any ingress."`

Any hint on what could go wrong?
