### ISSUE TITLE
Canonical Zone ID for endpoint:  is not found

### ISSUE THREAD

**Issue by onzo-operry** [linki/mate#85]
Hi, 

I have been banging my head at this for hours now, really not sure what I am doing so wrong. 
so I am trying the simplest setup where the ingress hosts *should* create r53 records in aws i assume?

any hints would be welcome 

if I remove the ingress-nginx , mate doesn't crash, but then again it doesn't really do anything either around creating records 

here is the log output 
=================
```bash
time="2017-02-22T21:22:33Z" level=info msg="[AWS] Listening for events..." 
time="2017-02-22T21:22:33Z" level=debug msg="[Synchronize] Sleeping for 1m0s..." 
time="2017-02-22T21:22:33Z" level=info msg="ADDED: default/ingress" 
time="2017-02-22T21:22:33Z" level=info msg="[AWS] Processing (a1.prodb.onzo.cloud., 10.55.53.140, )\n" 
time="2017-02-22T21:22:33Z" level=info msg="ADDED: kube-system/kube-dns" 
time="2017-02-22T21:22:33Z" level=warning msg="[Service] The load balancer of service 'kube-system/kube-dns' does not have any ingress." 
time="2017-02-22T21:22:33Z" level=info msg="ADDED: infra/elasticsearch-internal" 
time="2017-02-22T21:22:33Z" level=warning msg="[Service] The load balancer of service 'infra/elasticsearch-internal' does not have any ingress." 
time="2017-02-22T21:22:33Z" level=info msg="ADDED: infra/infra-ingress-ingress" 
time="2017-02-22T21:22:35Z" level=debug msg="Getting a page of ALBs of length: 0" 
time="2017-02-22T21:22:35Z" level=debug msg="Getting a page of ELBs of length: 4" 
time="2017-02-22T21:22:35Z" level=error msg="Canonical Zone ID for endpoint:  is not found" 
panic: runtime error: index out of range

goroutine 20 [running]:
panic(0x14d63a0, 0xc420016060)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/zalando-incubator/mate/consumers.(*awsConsumer).Process(0xc42040f300, 0xc42034b200, 0xc420379e68, 0x3)
        /home/master/workspace/teabag_mate_master-5HM4GNJPGTJMNQYAZYN6JFXPZ2TWYP4JPPHRCHUMWCZK6LHVMNQA/mate/_jenkins_build/go/src/github.com/zalando-incubator/mate/consumers/aws.go:195 +0x45a
github.com/zalando-incubator/mate/consumers.(*awsConsumer).Consume(0xc42040f300, 0xc4201cc1e0, 0xc4201cc240, 0xc4201cc2a0, 0xc4201a57b0)
        /home/master/workspace/teabag_mate_master-5HM4GNJPGTJMNQYAZYN6JFXPZ2TWYP4JPPHRCHUMWCZK6LHVMNQA/mate/_jenkins_build/go/src/github.com/zalando-incubator/mate/consumers/aws.go:173 +0x2eb
github.com/zalando-incubator/mate/consumers.(*SyncedConsumer).Consume(0xc42040f360, 0xc4201cc1e0, 0xc4201cc240, 0xc4201cc2a0, 0xc4201a57b0)
        <autogenerated>:10 +0x72
github.com/zalando-incubator/mate/controller.(*Controller).consumeEndpoints(0xc4201a5770)
        /home/master/workspace/teabag_mate_master-5HM4GNJPGTJMNQYAZYN6JFXPZ2TWYP4JPPHRCHUMWCZK6LHVMNQA/mate/_jenkins_build/go/src/github.com/zalando-incubator/mate/controller/controller.go:124 +0x58
created by github.com/zalando-incubator/mate/controller.(*Controller).Watch
        /home/master/workspace/teabag_mate_master-5HM4GNJPGTJMNQYAZYN6JFXPZ2TWYP4JPPHRCHUMWCZK6LHVMNQA/mate/_jenkins_build/go/src/github.com/zalando-incubator/mate/controller/controller.go:116 +0x61
```
ingress.yaml 
==========
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: a1.prodb.onzo.cloud
    http:
      paths:
      - backend:  
          serviceName: shop-svc
          servicePort: 80
```
service.yaml
==========
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:11111111111111:certificate/87d69a55-abcd-4cb6-b4b4-2f211f09241d
    service.betaubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  name: ingress-service
  annotations:
    zalando.org/dnsname: annotated-nginx.prod.onzo.cloud
  labels:
    component: ingress-service
spec:
  selector:
    component: nginx-ingress
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
```
nginx-rc.yaml
==========
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-controller
  labels:
    component: nginx-ingress
spec:
  replicas: 1
  selector:
    component: nginx-ingress
  template:
    metadata:
      labels:
        component: nginx-ingress
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        name: nginx-ingress
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=kube-system/default-http-backend
```
dummy backend
=============
```yaml
apiVersion: v1                                                                                                                                                                                                                     
kind: Service                                                                                                                                                                                                                       
metadata:                                                                                                                                                                                                                            
  name: shop-svc                                                                                                                                                                                                                       
  labels:                                                                                                                                                                                                                                
    app: shop                                                                                                                                                                                                                             
spec:                                                                                                                                                                                                                                      
  type: NodePort                                                                                                                                                                                                                              
  ports:                                                                                                                                                                                                                                       
  - port: 80                                                                                                                                                                                                                                    
    protocol: TCP                                                                                                                                                                                                                                 
    name: http
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```
mate.yaml
========
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mate
      annotations:
        iam.amazonaws.com/role: route53-kubernetes
    spec:
      containers:
      - name: mate
        image: registry.opensource.zalan.do/teapot/mate:v0.5.1
        env:
        - name: AWS_REGION
          value: eu-west-1
        args:
        - --producer=kubernetes
        - --kubernetes-format={{.Namespace}}-{{.Name}}.prodb.onzo.cloud
        - --consumer=aws
        - --aws-record-group-id=my-cluster
        - --debug
```

logs running sync-only
=================

time="2017-02-22T21:33:00Z" level=debug msg="[Synchronize] Sleeping for 1m0s..." 
[operry@peek01 default]$ kubectl logs mate-2617052176-2n5ws 
time="2017-02-22T21:33:00Z" level=debug msg="[Synchronize] Sleeping for 1m0s..." 
[operry@peek01 default]$ kubectl logs mate-2617052176-2n5ws 
time="2017-02-22T21:33:00Z" level=debug msg="[Synchronize] Sleeping for 1m0s..." 
[operry@peek01 default]$ kubectl logs mate-2617052176-2n5ws 
time="2017-02-22T21:33:00Z" level=debug msg="[Synchronize] Sleeping for 1m0s..." 
time="2017-02-22T21:34:00Z" level=info msg="[Synchronize] Synchronizing DNS entries..." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'default/kubernetes' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'default/shop-svc' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'infra/default-http-backend' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'infra/elasticsearch-discovery' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'infra/elasticsearch-internal' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'infra/idb-1-influxdb' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'infra/kibana-service' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'infra/logstash-internal' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'kube-system/default-http-backend' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'kube-system/kube-dns' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'kube-system/kubernetes-dashboard' does not have any ingress." 
time="2017-02-22T21:34:00Z" level=warning msg="[Service] The load balancer of service 'kube-system/tiller-deploy' does not have any ingress." 
time="2017-02-22T21:34:01Z" level=debug msg="Getting a page of ALBs of length: 0" 
time="2017-02-22T21:34:01Z" level=debug msg="Getting a page of ELBs of length: 4" 
time="2017-02-22T21:34:01Z" level=error msg="Canonical Zone ID for endpoint:  is not found" 
time="2017-02-22T21:34:02Z" level=warning msg="Hosted zone for endpoint: annotated-nginx.prod.onzo.cloud. is not found. Skipping record..." 
time="2017-02-22T21:34:02Z" level=debug msg="Getting a list of AWS RRS of length: 16" 
time="2017-02-22T21:34:02Z" level=debug msg="Records to be upserted:  [{\n  AliasTarget: {\n    DNSName: \"afc504560f9aa21e69d410a82ab2f03e-1278601154.eu-west-1.elb.amazonaws.com.\",\n    EvaluateTargetHealth: true,\n    HostedZoneId: \"Z32OAAAAAAAAAA\"\n  },\n  Name: \"infra-infra-ingress-ingress.prodb.onzo.cloud.\",\n  Type: \"A\"\n} {\n  Name: \"infra-infra-ingress-ingress.prodb.onzo.cloud.\",\n  ResourceRecords: [{\n      Value: \"\\\"mate:my-cluster\\\"\"\n    }],\n  TTL: 300,\n  Type: \"TXT\"\n}]" 
time="2017-02-22T21:34:02Z" level=debug msg="Records to be deleted:  []" 
time="2017-02-22T21:34:02Z" level=debug msg="[Synchronize] Sleeping for 1m0s..."
